### ISSUE TITLE
create stat randomizer

### ISSUE THREAD

**Issue by Ryan-Buckley1** [Rdoolz51/DDCharacterCreation#3]
create js using information from the dnd api to randomize stats:

- strength
- dexterity
- constitution
- intelligence
- wisdom
- charisma

**Comment by Rdoolz51** [comment]
*Added stat generator. The page itself will need designed, but the code for the stat randomizer is there

**Comment by Rdoolz51** [comment]
The code is in statGenerator.js, you can link to it and put it into your stats.html file or change the js entirely, up to you!

**Comment by Ryan-Buckley1** [comment]
completed. added some new buttons and sent items to local storage
