### ISSUE TITLE
LIMIT # of times player can reroll stats to 1

### ISSUE THREAD

**Issue by Rdoolz51** [Rdoolz51/DDCharacterCreation#30]

**Comment by Ryan-Buckley1** [comment]
I set it to they can only roll their stats once then the button disappears. So they get what they get unless you wanna change that. 
If you wanna change it all you have to do it change the function I put on the button click to not hide the #statBtn

**Comment by Rdoolz51** [comment]
I added a counter called mulliganCounter to the randomize stats function. Every time the button is pressed it adds 1 to the counter. When the counter == 2 (they rolled, then rerolled once) the button will hide
