### ISSUE TITLE
Add Fantasy Names to Array at the top of Names.js

### ISSUE THREAD

**Issue by Rdoolz51** [Rdoolz51/DDCharacterCreation#8]
* Delete all of the names that are in there only for testing purposes. 
* Add fantasy first and last names to the correct arrays inside of the Names.js file
* Find at least 100 first and 100 last names to put in the array. Some can sounds silly, its just a fantasy name

**Comment by Ryan-Buckley1** [comment]
do we want to just add a new js file for this so that it separates it from the main js page? sort of like we did for the quiz app?

**Comment by Ryan-Buckley1** [comment]
Mohammad got this completed! Good Job!
